name       : bspwm
version    : 0.9.3
release    : 3
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.3.tar.gz : b356e3ff5754c63c94b36d904274c0ba16f9a8494e78a1c93bb23113f891bc9d
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
