name       : bspwm
version    : 0.9.1
release    : 1
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.1.tar.gz : 02bb58a307acdec242eb4b8a62764ed53d01c30474dfb1bc09812d943773bb85
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
