name       : bspwm
version    : 0.9.10
release    : 9
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.10.tar.gz : 0d0f5e465b9c27a5c2143c86189392fa297fad55253b9ed8f6854473d3928f8f
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
setup      : |
    %apply_patches
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
