name       : bspwm
version    : 0.9.4
release    : 4
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.4.tar.gz : 7c921e8d8f98c2c7b5e0d389a7838fc82b819adc773f931d46590db9fe06597a
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
