name       : bspwm
version    : 0.9.7
release    : 6
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.7.tar.gz : 336c28a272b2a3d5f5324a4634143ff8fdb07648c110ac48b1a480a50e583a5d
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
