name       : bspwm
version    : 0.9.5
release    : 5
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.5.tar.gz : 273591baf6a15d317cfedf4a423c51c132c52dd05b0328d6994f7bdc3982f782
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
