name       : bspwm
version    : 0.9.8
release    : 7
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.8.tar.gz : 8bf670227b3e3c91b94df0834daf2b3da36bbac196c5bcc65353b3eb5983afa6
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
setup      : |
    %patch -p1 < $pkgfiles/0001-Honor-single_monocle-in-set_hidden.patch
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
